/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-primary-fixed-variant": "#474747",
        "on-surface-variant": "#434655",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#5e5e5e",
        "outline-variant": "#c3c6d7",
        "secondary-container": "#316bf3",
        "surface-variant": "#e1e3e4",
        "primary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#00174b",
        "on-background": "#191c1d",
        "on-primary-fixed": "#1b1b1b",
        "error-container": "#ffdad6",
        "surface": "#f8f9fa",
        "on-secondary": "#ffffff",
        "primary-container": "#6d6d6d",
        "surface-dim": "#d9dadb",
        "tertiary": "#3e3fcc",
        "on-tertiary-container": "#f1eeff",
        "background": "#f8f9fa",
        "tertiary-fixed-dim": "#c0c1ff",
        "inverse-primary": "#c6c6c6",
        "on-primary-container": "#f0f0f0",
        "surface-container": "#edeeef",
        "outline": "#737686",
        "surface-container-highest": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed": "#dbe1ff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-surface": "#191c1d",
        "primary-fixed-dim": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "secondary": "#0051d5",
        "primary": "#555555",
        "surface-container-high": "#e7e8e9",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e1e0ff",
        "error": "#ba1a1a",
        "tertiary-container": "#585be6",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#07006c",
        "on-secondary-container": "#fefcff",
        gradient: {
          '1': 'var(--gradient-1)',
          '2': 'var(--gradient-2)',
          '3': 'var(--gradient-3)',
          '4': 'var(--gradient-4)',
          '5': 'var(--gradient-5)',
        }
      },
      fontFamily: {
        "headline": ["Host Grotesk", "sans-serif"],
        "body": ["Host Grotesk", "sans-serif"],
        "label": ["Host Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}